### ISSUE TITLE
#TK10 Seccion Registro Responsive

### ISSUE THREAD

**Issue by oliverio97** [oliverio97/Proyecto-integrador---ISPC#40]
El formulario de registro no es responsive. Al achicar la pagina hasta el minimo tamaño, el titulo del formulario sale de su contenedor de origen.

**Comment by JulianMeneses1** [comment]
Ahí estuve haciendo algunos cambios en el formulario, lo que no logro es hacerlo totalmente responsive cosa de que en pantallas chicas los inputs ocupen el 100% del ancho y se pongan por lo tanto uno abajo de otro, y no de a 2 como estan ahora.

**Comment by JulianMeneses1** [comment]
Ahora creé un nuevo formulario con el formato grilla (filas y columnas), me parece que se adapta un poco más a las variaciones en el tamaño de la pantalla.

**Comment by C-Adrian-A** [comment]
gracias por los aportes, no me di cuenta de probarlo antes de subir!
